version: '3.6'

services:
  postgres:
    container_name: blog_postgres
    image: postgres:13.1
    environment:
      POSTGRES_USER: davi
      POSTGRES_PASSWORD: davi
      POSTGRES_DB: the_toy_project
    volumes:
      - blog_postgres:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    container_name: blog_redis
    image: redis:6.0.9
    restart: on-failure

  blogapp:
    container_name: blog_app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    image: blogapp

volumes:
  blog_postgres:
    driver: local
  blog_app:
    driver: local
