version: '3.6'

services:
  postgres:
    container_name: blog_postgres
    image: postgres:13.1
    environment:
      POSTGRES_USER: davi
      POSTGRES_PASSWORD: davi
      POSTGRES_DB: the_toy_project
    volumes:
      - blog_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - the_toy_project
    restart: unless-stopped

  redis:
    container_name: blog_redis
    image: redis:6.0.9
    restart: on-failure
    ports:
      - "6379:6379"

networks:
  the_toy_project:
    driver: bridge

volumes:
  blog_postgres:
    driver: local
